name: Build docker images
on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build docker image and push it to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: filesender/filesender
          tag_with_ref: true
          tag_with_sha: true
          path: docker
          build_args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%Sz'),VCS_REF=${GITHUB_SHA:8},REF=${GITHUB_REF}

